version: "3"

services: 
    server:
        build: ./server
        command: npm start
        restart: always
        ports: 
            - "3333:3333"
        volumes: 
            - ./server:/usr/src/node-jest/server
            - /usr/src/node-jest/server/node_modules
        environment:
            DB_HOST: postgres
            DB_USER: postgres
            DB_PASSWORD: mysecretpassword
            DB_NAME: jest
        depends_on: 
            - postgres
    postgres:
        image: postgres:11
        ports: 
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_USER: postgres
        volumes: 
            - ./postgres_data:/var/lib/postgresql/data

        